name: 'Install dependencies'
description: 'Set up node and install dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: '24.x'
        cache: npm

    - run: npm ci
      shell: bash
