name: GitHub Script
description: An action for running simple scripts with a GitHub client
branding:
  color: blue
  icon: code
inputs:
  script:
    description: The script to run
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    required: true
  debug:
    description: Whether to tell the GitHub client to log details of its requests
    default: false
  user-agent:
    description: An optional user-agent string
    default: actions/github-script
  previews:
    description: A comma-separated list of API previews to accept
outputs:
  result:
    description: The return value of the script, stringified with `JSON.stringify`
runs:
  using: node12
  main: main.js
